AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: UploadFiletoS3 Lambda function template for Application Load Balancer Lambda as target

Outputs:
  UploadFiletoS3FunctionARN:
    Description: "ARN of the UploadFiletoS3 Lambda function"
    Value: !GetAtt UploadFiletoS3Function.Arn

Parameters:
  BucketName:
    Type: String
    Default: "myBucket"

Resources:
  UploadFiletoS3Function:
    Type: AWS::Serverless::Function
    Properties:
      Description: An Application Load Balancer Lambda Target that upload files to S3
      Handler: uploadfile_39.lambda_handler
      # https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/lambda-runtimes.html
      Runtime: python3.9
      CodeUri: ./
      Timeout: 300
      Policies:
        - S3WritePolicy:
            BucketName: !Ref BucketName
